language: node_js
node_js:
- 'v7.9.0'
services:
- mongodb
cache:
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: AKIAJW4VB2PSSWJ74JLQ
  secret_access_key: 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
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: vimal1083/travis-deployment
  bucket: travis-deploy-code
  region: us-east-2
- provider: codedeploy
  access_key_id: AKIAJW4VB2PSSWJ74JLQ
  secret_access_key: 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
  bucket: travis-deploy-code
  key: latest.zip
  bundle_type: zip
  application: travis-trigger-deployment
  deployment_group: travis-trigger-deployment-group
  region: us-east-2
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip