version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/myapp
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
  ApplicationStart:
    - location: scripts/after_start.sh
  ApplicationStop:
    - location: scripts/app_stop.sh
