version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/myapp
hooks:
  AfterInstall:
    - location: scripts/after_instal_delete_node_modules.sh
      runas: root
    - location: scripts/after_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/app_start.sh
      runas: ubuntu
  ApplicationStop:
    - location: scripts/app_stop.sh
      runas: ubuntu
