version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/myapp
hooks:  
  ApplicationStart:
    - location: scripts/app_start.sh
  ApplicationStop:
    - location: scripts/app_stop.sh
